- block:
  - name: Build sandalphon image and push it to GitHub container registry
    docker_image:
      source: build
      force_source: yes
      name: ghcr.io/ia-toki/judgels/sandalphon
      push: yes
      build:
        path: "{{ playbook_dir }}/../../../judgels-backends/sandalphon/sandalphon-play-app"
        args:
          VCS_REF: "{{ lookup('env', 'GITHUB_SHA') }}"
