name: ci

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50

      - id: changed-files
        name: Check changed files
        run: python3 ci/check-changed-files.py | bash

      - name: Set up JDK
        if: steps.changed-files.outputs.gradle == '1'
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Use Gradle cache
        if: steps.changed-files.outputs.gradle == '1'
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Test Michael
        if: steps.changed-files.outputs.michael == '1'
        run: ./judgels-backends/gradlew -p judgels-backends/michael check

      - name: Test Jophiel
        if: steps.changed-files.outputs.jophiel == '1'
        run: ./judgels-backends/gradlew -p judgels-backends/jophiel check

      - name: Test Sandalphon
        if: steps.changed-files.outputs.sandalphon == '1'
        run: ./judgels-backends/gradlew -p judgels-backends/sandalphon check

      - name: Test Uriel
        if: steps.changed-files.outputs.uriel == '1'
        run: ./judgels-backends/gradlew -p judgels-backends/uriel check

      - name: Test Jerahmeel
        if: steps.changed-files.outputs.jerahmeel == '1'
        run: ./judgels-backends/gradlew -p judgels-backends/jerahmeel check

      - name: Test Gabriel
        if: steps.changed-files.outputs.gabriel == '1'
        run: ./judgels-backends/gradlew -p judgels-backends/gabriel check

      - name: Set up Node
        if: steps.changed-files.outputs.yarn == '1'
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 10.16

      - name: Get Yarn cache directory path
        if: steps.changed-files.outputs.yarn == '1'
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Yarn cache
        if: steps.changed-files.outputs.yarn == '1'
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Test Raphael
        if: steps.changed-files.outputs.raphael == '1'
        run: yarn --cwd=`pwd`/judgels-frontends/raphael install && yarn --cwd=`pwd`/judgels-frontends/raphael ci

  build:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      CONTAINER_REGISTRY_TOKEN: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50

      - name: Set up Docker
        run: pipx inject ansible-core docker six

      - id: changed-files
        name: Check changed files
        run: python3 ci/check-changed-files.py | bash

      - name: Set up JDK
        if: steps.changed-files.outputs.gradle == '1'
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Use Gradle cache
        if: steps.changed-files.outputs.gradle == '1'
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Michael
        if: steps.changed-files.outputs.michael == '1'
        run: ./deployment/scripts/build_michael.sh

      - name: Build Jophiel
        if: steps.changed-files.outputs.jophiel == '1'
        run: ./deployment/scripts/build_jophiel.sh

      - name: Build Sandalphon
        if: steps.changed-files.outputs.sandalphon == '1'
        run: ./deployment/scripts/build_sandalphon.sh

      - name: Build Uriel
        if: steps.changed-files.outputs.uriel == '1'
        run: ./deployment/scripts/build_uriel.sh

      - name: Build Jerahmeel
        if: steps.changed-files.outputs.jerahmeel == '1'
        run: ./deployment/scripts/build_jerahmeel.sh

      - name: Build Gabriel
        if: steps.changed-files.outputs.gabriel == '1'
        run: ./deployment/scripts/build_gabriel.sh

      - name: Set up Node
        if: steps.changed-files.outputs.yarn == '1'
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 10.16

      - name: Get Yarn cache directory path
        if: steps.changed-files.outputs.yarn == '1'
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Yarn cache
        if: steps.changed-files.outputs.yarn == '1'
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build Raphael
        if: steps.changed-files.outputs.raphael == '1'
        run: ./deployment/scripts/build_raphael.sh

  deploy-tlx-staging:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50

      - name: Check out deployment repository
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.TLX_STAGING_DEPLOYMENT_REPOSITORY }}
          token: ${{ secrets.TLX_STAGING_DEPLOYMENT_TOKEN }}
          path: deployment/ansible/dist

      - name: Prepare staging environment SSH key
        run: chmod 600 deployment/ansible/dist/deployment_rsa

      - id: changed-files
        name: Check changed files
        run: python3 ci/check-changed-files.py | bash

      - name: Deploy Michael
        if: steps.changed-files.outputs.michael == '1'
        run: |
          eval "$(ssh-agent -s)"
          ssh-add deployment/ansible/dist/deployment_rsa
          ./deployment/scripts/deploy_michael.sh

      - name: Deploy Jophiel
        if: steps.changed-files.outputs.jophiel == '1'
        run: |
          eval "$(ssh-agent -s)"
          ssh-add deployment/ansible/dist/deployment_rsa
          ./deployment/scripts/deploy_jophiel.sh

      - name: Deploy Sandalphon
        if: steps.changed-files.outputs.sandalphon == '1'
        run: |
          eval "$(ssh-agent -s)"
          ssh-add deployment/ansible/dist/deployment_rsa
          ./deployment/scripts/deploy_sandalphon.sh

      - name: Deploy Uriel
        if: steps.changed-files.outputs.uriel == '1'
        run: |
          eval "$(ssh-agent -s)"
          ssh-add deployment/ansible/dist/deployment_rsa
          ./deployment/scripts/deploy_uriel.sh

      - name: Deploy Jerahmeel
        if: steps.changed-files.outputs.jerahmeel == '1'
        run: |
          eval "$(ssh-agent -s)"
          ssh-add deployment/ansible/dist/deployment_rsa
          ./deployment/scripts/deploy_jerahmeel.sh

      - name: Deploy Raphael
        if: steps.changed-files.outputs.raphael == '1'
        run: |
          eval "$(ssh-agent -s)"
          ssh-add deployment/ansible/dist/deployment_rsa
          ./deployment/scripts/deploy_raphael.sh
